Update README.md
Super-excited for this tool, thanks for working on this! Been tracking the RFC's, but glad to see something in action.
First proposed change is just to move to the official `bazelbuild/rules_rust`.
Second is a bit more interesting - because of [how Cargo treats pre-1.0](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) it will actually try to pull in `0.3.9` instead of `0.3.6`. This triggers *also* including `0.4.1` because `0.3.9` has a dependency on `0.4` [here](https://github.com/rust-lang-nursery/log/commit/c9463807805c6d3b48a82bdb627b8e1e329546dc). Finally, because now we have generated a `log` dependency for `0.3.9` and `0.4.1`, bazel blows up because the same alias is being used twice:

```
INFO: Analysed target //hello_world:hello_world (4 packages loaded).                                                                   
INFO: Found 1 target...          
ERROR: /home/.../00fa756a34c1c23b3e40e8a061f5fbca/external/raze__log__0_3_9/BUILD.bazel:21:1: error executing shell command: 'set -e; rm -rf bazel-out/k8-fastbuild/bin/external/raze__log__0_3_9/log.deps; mkdir bazel-out/k8-fastbuild/bin/external/raze__log__0_3_9/log.deps                                  
 ln -sf ../../raze__log__0_4_1/liblog.rlib bazel-ou...' failed (Exit 101)                                                              
error[E0519]: the current crate is indistinguishable from one of its dependencies: it has the same crate-name `log` and was compiled with the same `-C metadata` arguments. This will result in symbol conflicts between the two.                                             
   --> external/raze__log__0_3_9/src/lib.rs:202:1                  
    |                            
202 | extern crate log;          
    | ^^^^^^^^^^^^^^^^^          

Target //hello_world:hello_world failed to build                   
Use --verbose_failures to see the command lines of failed build steps.                                                                 
INFO: Elapsed time: 0.417s, Critical Path: 0.11s                   
FAILED: Build did NOT complete successfully                        
ERROR: Build failed. Not running target
```